//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketClient.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TicketClient.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 https://kyfw.12306.cn/otn/confirmPassenger/confirmSingleForQueueAsys 的本地化字符串。
        /// </summary>
        internal static string AutoConfirmOrderUrl {
            get {
                return ResourceManager.GetString("AutoConfirmOrderUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://kyfw.12306.cn/otn/confirmPassenger/getQueueCountAsync 的本地化字符串。
        /// </summary>
        internal static string AutoOrderQueueCountUrl {
            get {
                return ResourceManager.GetString("AutoOrderQueueCountUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://kyfw.12306.cn/otn/confirmPassenger/autoSubmitOrderRequest 的本地化字符串。
        /// </summary>
        internal static string AutoSubmitOrderUrl {
            get {
                return ResourceManager.GetString("AutoSubmitOrderUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://kyfw.12306.cn/otn/queryOrder/cancelNoCompleteMyOrder 的本地化字符串。
        /// </summary>
        internal static string CancelNoCompleteOrderUrl {
            get {
                return ResourceManager.GetString("CancelNoCompleteOrderUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap check {
            get {
                object obj = ResourceManager.GetObject("check", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 https://kyfw.12306.cn/otn/confirmPassenger/checkOrderInfo 的本地化字符串。
        /// </summary>
        internal static string CheckOrderInfoUrl {
            get {
                return ResourceManager.GetString("CheckOrderInfoUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://kyfw.12306.cn/otn/passcodeNew/checkRandCodeAnsyn 的本地化字符串。
        /// </summary>
        internal static string CheckVerifyCodeUrl {
            get {
                return ResourceManager.GetString("CheckVerifyCodeUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap close {
            get {
                object obj = ResourceManager.GetObject("close", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 https://kyfw.12306.cn/otn/confirmPassenger/confirmSingleForQueue 的本地化字符串。
        /// </summary>
        internal static string ConfirmOrderUrl {
            get {
                return ResourceManager.GetString("ConfirmOrderUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://kyfw.12306.cn/otn/confirmPassenger/getPassengerDTOs 的本地化字符串。
        /// </summary>
        internal static string ContactUrl {
            get {
                return ResourceManager.GetString("ContactUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 (Icon) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon ic_train {
            get {
                object obj = ResourceManager.GetObject("ic_train", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 https://kyfw.12306.cn/otn/leftTicket/init 的本地化字符串。
        /// </summary>
        internal static string InitTicketQueryUrl {
            get {
                return ResourceManager.GetString("InitTicketQueryUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://kyfw.12306.cn/otn/login/loginAysnSuggest 的本地化字符串。
        /// </summary>
        internal static string LoginUrl {
            get {
                return ResourceManager.GetString("LoginUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://kyfw.12306.cn/otn/passcodeNew/getPassCodeNew?module=login&amp;rand=sjrand 的本地化字符串。
        /// </summary>
        internal static string LoginVerifyCodeUrl {
            get {
                return ResourceManager.GetString("LoginVerifyCodeUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://kyfw.12306.cn/otn/login/loginOut 的本地化字符串。
        /// </summary>
        internal static string LogOffUrl {
            get {
                return ResourceManager.GetString("LogOffUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://kyfw.12306.cn/otn/queryOrder/queryMyOrderNoComplete 的本地化字符串。
        /// </summary>
        internal static string NoCompleteOrderUrl {
            get {
                return ResourceManager.GetString("NoCompleteOrderUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://kyfw.12306.cn/otn/confirmPassenger/getQueueCount 的本地化字符串。
        /// </summary>
        internal static string OrderQueueCountUrl {
            get {
                return ResourceManager.GetString("OrderQueueCountUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://kyfw.12306.cn/otn/confirmPassenger/initDc 的本地化字符串。
        /// </summary>
        internal static string OrderTokenUrl {
            get {
                return ResourceManager.GetString("OrderTokenUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://kyfw.12306.cn/otn/confirmPassenger/queryOrderWaitTime 的本地化字符串。
        /// </summary>
        internal static string OrderWaitTimeUrl {
            get {
                return ResourceManager.GetString("OrderWaitTimeUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://kyfw.12306.cn/otn/resources/js/framework/station_name.js 的本地化字符串。
        /// </summary>
        internal static string StationNameUrl {
            get {
                return ResourceManager.GetString("StationNameUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://kyfw.12306.cn/otn/leftTicket/submitOrderRequest 的本地化字符串。
        /// </summary>
        internal static string SubmitOrderUrl {
            get {
                return ResourceManager.GetString("SubmitOrderUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://kyfw.12306.cn/otn/passcodeNew/getPassCodeNew?module=passenger&amp;rand=randp 的本地化字符串。
        /// </summary>
        internal static string SubmitOrderVerifyCodeUrl {
            get {
                return ResourceManager.GetString("SubmitOrderVerifyCodeUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://kyfw.12306.cn/otn/login/checkUser 的本地化字符串。
        /// </summary>
        internal static string UserIsOnlineUrl {
            get {
                return ResourceManager.GetString("UserIsOnlineUrl", resourceCulture);
            }
        }
    }
}
